"""
Core domain models.

Design notes:
- Project.id is the SQL primary key, generated once by the database. There is
  no client-side ID generation anywhere — this is what makes the old
  "duplicate save" bug structurally impossible: a project either exists (one
  row, one id) or it doesn't. Saving again is always an UPDATE, never an
  accidental INSERT.
- Tenant is a real row, not a hardcoded "demo-tenant" string. Every tenant
  is created explicitly (see routers/tenants.py) — there is no default tenant.
"""
from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text, JSON, Enum as SAEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base
import enum
import uuid


def gen_uuid() -> str:
    return str(uuid.uuid4())


class Tenant(Base):
    __tablename__ = "tenants"
    id = Column(String, primary_key=True, default=gen_uuid)
    name = Column(String(120), unique=True, nullable=False, index=True)
    plan = Column(String(40), default="free")
    credit_balance = Column(Integer, default=1000)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    users = relationship("User", back_populates="tenant", cascade="all, delete-orphan")
    projects = relationship("Project", back_populates="tenant", cascade="all, delete-orphan")


class User(Base):
    __tablename__ = "users"
    id = Column(String, primary_key=True, default=gen_uuid)
    tenant_id = Column(String, ForeignKey("tenants.id"), nullable=False)
    email = Column(String(254), unique=True, nullable=False, index=True)
    name = Column(String(200))
    hashed_password = Column(String, nullable=False)
    role = Column(String(40), default="Member")  # Owner | Admin | Member
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    tenant = relationship("Tenant", back_populates="users")


class ProjectStatus(str, enum.Enum):
    DRAFT = "draft"
    GENERATING = "generating"
    READY = "ready"
    PUSHED = "pushed"
    ARCHIVED = "archived"


class Project(Base):
    """
    A single generated project. One row per project — the primary key is the
    one and only source of truth for identity, generated by Postgres itself.
    """
    __tablename__ = "projects"
    id = Column(String, primary_key=True, default=gen_uuid)
    tenant_id = Column(String, ForeignKey("tenants.id"), nullable=False, index=True)
    owner_id = Column(String, ForeignKey("users.id"), nullable=True)

    name = Column(String(200), nullable=False)
    intent = Column(Text, nullable=False)          # what the user described
    description = Column(Text)                      # AI's one-line summary
    architecture = Column(JSON, default=list)        # [{layer, tech, desc}, ...]
    files = Column(JSON, default=dict)                # {path: content}
    status = Column(SAEnum(ProjectStatus), default=ProjectStatus.DRAFT)

    repo_provider = Column(String(40))   # github | gitlab | bitbucket | azure
    repo_url = Column(String(500))
    repo_branch = Column(String(120))
    repo_owner = Column(String(200))
    repo_name = Column(String(200))

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    tenant = relationship("Tenant", back_populates="projects")
    deploy_events = relationship("DeployEvent", back_populates="project", cascade="all, delete-orphan")


class DeployEvent(Base):
    """One row per deployment signal received via webhook or manual ping."""
    __tablename__ = "deploy_events"
    id = Column(String, primary_key=True, default=gen_uuid)
    project_id = Column(String, ForeignKey("projects.id"), nullable=False, index=True)

    environment = Column(String(80), default="production")
    version = Column(String(120))
    deployed_by = Column(String(120))
    url = Column(String(500))
    simulated = Column(Boolean, default=False)

    received_at = Column(DateTime(timezone=True), server_default=func.now())

    project = relationship("Project", back_populates="deploy_events")


class AuditLog(Base):
    __tablename__ = "audit_log"
    id = Column(String, primary_key=True, default=gen_uuid)
    tenant_id = Column(String, ForeignKey("tenants.id"), nullable=False, index=True)
    actor = Column(String(200))
    action = Column(String(300))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
